/*
 * DialogoRelogio.java
 *
 * Created on 17 de Abril de 2009, 14:12
 */

package br.org.serpro.pontofacil.view;

import java.text.ParseException;
import java.util.Date;

import javax.swing.JFormattedTextField;
import javax.swing.text.MaskFormatter;

import br.org.serpro.pontofacil.entity.Turno;

/**
 *
 * @author  72767863587
 */
public class DialogoRelogio extends javax.swing.JDialog {
	MaskFormatter hora;
	
    /** Creates new form DialogoRelogio */
    public DialogoRelogio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        try {
			hora = new MaskFormatter("##:##");
                        hora.setPlaceholderCharacter('_');
		} catch (ParseException e) {
			e.printStackTrace();
		}
        
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHrEnt1Turno = new JFormattedTextField(hora);
        txtHrSai1Turno = new JFormattedTextField(hora);
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtHrEnt2Turno = new JFormattedTextField(hora);
        txtHrSai2Turno = new JFormattedTextField(hora);
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtHrEnt1TurnoExt = new JFormattedTextField(hora);
        txtHrSai1TurnoExt = new JFormattedTextField(hora);
        jLayeredPane6 = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtHrEnt2TurnoExt = new javax.swing.JTextField();
        txtHrSai2TurnoExt = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        btlCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("1 Turno"));

        jLabel5.setText("Saída");
        jLabel5.setBounds(190, 20, 50, 19);
        jLayeredPane3.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setText("Entrada");
        jLabel6.setBounds(20, 20, 50, 19);
        jLayeredPane3.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtHrEnt1Turno.setBounds(80, 20, 90, 23);
        jLayeredPane3.add(txtHrEnt1Turno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtHrSai1Turno.setBounds(250, 20, 90, 23);
        jLayeredPane3.add(txtHrSai1Turno, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createTitledBorder("2 Turno"));

        jLabel7.setText("Saída");
        jLabel7.setBounds(190, 20, 50, 19);
        jLayeredPane4.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setText("Entrada");
        jLabel8.setBounds(20, 20, 50, 19);
        jLayeredPane4.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtHrEnt2Turno.setBounds(80, 20, 90, 23);
        jLayeredPane4.add(txtHrEnt2Turno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtHrSai2Turno.setBounds(250, 20, 90, 23);
        jLayeredPane4.add(txtHrSai2Turno, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane5.setBorder(javax.swing.BorderFactory.createTitledBorder("1 Turno Extra"));

        jLabel9.setText("Saída");
        jLabel9.setBounds(190, 20, 50, 19);
        jLayeredPane5.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setText("Entrada");
        jLabel10.setBounds(20, 20, 50, 19);
        jLayeredPane5.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtHrEnt1TurnoExt.setBounds(80, 20, 90, 23);
        jLayeredPane5.add(txtHrEnt1TurnoExt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtHrSai1TurnoExt.setBounds(250, 20, 90, 23);
        jLayeredPane5.add(txtHrSai1TurnoExt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane6.setBorder(javax.swing.BorderFactory.createTitledBorder("2 Turno Extra"));

        jLabel11.setText("Saída");
        jLabel11.setBounds(190, 20, 50, 19);
        jLayeredPane6.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel12.setText("Entrada");
        jLabel12.setBounds(20, 20, 50, 19);
        jLayeredPane6.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtHrEnt2TurnoExt.setBounds(80, 20, 90, 23);
        jLayeredPane6.add(txtHrEnt2TurnoExt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtHrSai2TurnoExt.setBounds(250, 20, 90, 23);
        jLayeredPane6.add(txtHrSai2TurnoExt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnConfirmar.setText("Confirmar");

        btlCancel.setText("Cancelar");
        btlCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                            .addComponent(jLayeredPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                            .addComponent(jLayeredPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                            .addComponent(jLayeredPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btlCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btlCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-410)/2, (screenSize.height-343)/2, 410, 343);
    }// </editor-fold>//GEN-END:initComponents

    private void btlCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btlCancelActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoRelogio dialog = new DialogoRelogio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlCancel;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JTextField txtHrEnt1Turno;
    private javax.swing.JTextField txtHrEnt1TurnoExt;
    private javax.swing.JTextField txtHrEnt2Turno;
    private javax.swing.JTextField txtHrEnt2TurnoExt;
    private javax.swing.JTextField txtHrSai1Turno;
    private javax.swing.JTextField txtHrSai1TurnoExt;
    private javax.swing.JTextField txtHrSai2Turno;
    private javax.swing.JTextField txtHrSai2TurnoExt;
    // End of variables declaration//GEN-END:variables
    
    
    public Date obterHrEnt1Turno(){
    	txtHrEnt1Turno.setEditable(true);
        txtHrSai1Turno.setEditable(false);
        txtHrEnt2Turno.setEditable(false);
        txtHrSai2Turno.setEditable(false);
      	txtHrEnt1TurnoExt.setEditable(false);
        txtHrSai1TurnoExt.setEditable(false);
        txtHrEnt2TurnoExt.setEditable(false);
        txtHrSai2TurnoExt.setEditable(false);

        return new Date();
    }
}
